# -*- coding: utf-8 -*-
"""Preprocesing_And_Viualizatin_of_Diabete_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xoZEVgp5b96RgrhUIRNC9MVNowVjmDl
"""

import pandas as pd
import numpy as np
data=pd.read_csv('/content/drive/MyDrive/diabetes.csv')

data.head()

data.info()

data.describe()

data.nunique()

data.isnull().sum()

import matplotlib.pyplot as plt
x=data['BMI']
y=data['Age']
plt.scatter(x,y)
plt.ylabel('Age')
plt.xlabel('BMI')
plt.show()

plt.plot(x)

plt.hist(y)
plt.show()

plt.bar(x,y)
plt.xlabel('BMI')
plt.ylabel('Age')
plt.show()

A=data['Outcome']
plt.pie(A)
plt.show()

import seaborn as sns
sns.lineplot(x)

sns.scatterplot(x=x,y=y,data=data)

sns.barplot(x=data['Outcome'],y=y,data=data)

sns.displot(x=y)

sns.distplot(x=y)

sns.boxplot(y=x,data=data)

sns.pairplot(data,hue='Outcome')

sns.heatmap(data.corr(),annot=True)